// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

package com.wonderzh.cooser.protocol;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datameter.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mode = 1;</code>
     * @return The mode.
     */
    String getMode();
    /**
     * <code>string mode = 1;</code>
     * @return The bytes for mode.
     */
    com.google.protobuf.ByteString
        getModeBytes();

    /**
     * <code>string protocol = 2;</code>
     * @return The protocol.
     */
    String getProtocol();
    /**
     * <code>string protocol = 2;</code>
     * @return The bytes for protocol.
     */
    com.google.protobuf.ByteString
        getProtocolBytes();

    /**
     * <code>int64 uuid = 3;</code>
     * @return The uuid.
     */
    long getUuid();

    /**
     * <code>string authorization = 4;</code>
     * @return The authorization.
     */
    String getAuthorization();
    /**
     * <code>string authorization = 4;</code>
     * @return The bytes for authorization.
     */
    com.google.protobuf.ByteString
        getAuthorizationBytes();

    /**
     * <code>.request.LfData lf_data = 5;</code>
     * @return Whether the lfData field is set.
     */
    boolean hasLfData();
    /**
     * <code>.request.LfData lf_data = 5;</code>
     * @return The lfData.
     */
    com.wonderzh.cooser.protocol.RequestProto.LfData getLfData();
    /**
     * <code>.request.LfData lf_data = 5;</code>
     */
    com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder getLfDataOrBuilder();

    /**
     * <code>.request.HfData hf_data = 6;</code>
     * @return Whether the hfData field is set.
     */
    boolean hasHfData();
    /**
     * <code>.request.HfData hf_data = 6;</code>
     * @return The hfData.
     */
    com.wonderzh.cooser.protocol.RequestProto.HfData getHfData();
    /**
     * <code>.request.HfData hf_data = 6;</code>
     */
    com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder getHfDataOrBuilder();

    /**
     * <code>.request.Instruction instruction = 7;</code>
     * @return Whether the instruction field is set.
     */
    boolean hasInstruction();
    /**
     * <code>.request.Instruction instruction = 7;</code>
     * @return The instruction.
     */
    com.wonderzh.cooser.protocol.RequestProto.Instruction getInstruction();
    /**
     * <code>.request.Instruction instruction = 7;</code>
     */
    com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder getInstructionOrBuilder();

    /**
     * <code>.response.Response response = 8;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.response.Response response = 8;</code>
     * @return The response.
     */
    com.wonderzh.cooser.protocol.ResponseProto.Response getResponse();
    /**
     * <code>.response.Response response = 8;</code>
     */
    com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>.google.protobuf.Any any = 9;</code>
     * @return Whether the any field is set.
     */
    boolean hasAny();
    /**
     * <code>.google.protobuf.Any any = 9;</code>
     * @return The any.
     */
    com.google.protobuf.Any getAny();
    /**
     * <code>.google.protobuf.Any any = 9;</code>
     */
    com.google.protobuf.AnyOrBuilder getAnyOrBuilder();

    /**
     * <code>.generic.JsonObj json = 10;</code>
     * @return Whether the json field is set.
     */
    boolean hasJson();
    /**
     * <code>.generic.JsonObj json = 10;</code>
     * @return The json.
     */
    com.wonderzh.cooser.protocol.GenericProto.JsonObj getJson();
    /**
     * <code>.generic.JsonObj json = 10;</code>
     */
    com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder getJsonOrBuilder();

    public com.wonderzh.cooser.protocol.MessageProto.Message.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code datameter.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datameter.Message)
      MessageOrBuilder,ProtocolMessage {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      mode_ = "";
      protocol_ = "";
      authorization_ = "";
    }

    /**
     * -------------自定义接口--------------
     */
    @Override
    public void setProtocol(String str) {
      this.protocol_ = str;
    }

    @Override
    public void setUuid(long id) {
      this.uuid_ = id;
    }

    @Override
    public void setMode(String mode) {
      this.mode_ = mode;
    }

    @Override
    public void setAuthorization(String authorization) {
      this.authorization_ = authorization;
    }

    @Override
    public ProtocolMessage newInstance() {
      return (ProtocolMessage) newInstance(null);
    }

    @Override
    public Object getBody() {
      return body_;
    }

    @Override
    public void setResponse(Response response) {
      this.body_ = response;
      this.bodyCase_ = 8;
    }

    @Override
    public void setJsonBody(GenericProto.JsonObj jsonBody) {
      this.body_ = jsonBody;
      this.bodyCase_ = 10;
    }

    @Override
    public Response newResponseInstance() {
      ResponseProto.Response.Builder builder = ResponseProto.Response.newBuilder();
      return builder.build();
    }
    /**
     * -------------自定义接口结束--------------
     */
    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              mode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              protocol_ = s;
              break;
            }
            case 24: {

              uuid_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              authorization_ = s;
              break;
            }
            case 42: {
              com.wonderzh.cooser.protocol.RequestProto.LfData.Builder subBuilder = null;
              if (bodyCase_ == 5) {
                subBuilder = ((com.wonderzh.cooser.protocol.RequestProto.LfData) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.wonderzh.cooser.protocol.RequestProto.LfData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wonderzh.cooser.protocol.RequestProto.LfData) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 5;
              break;
            }
            case 50: {
              com.wonderzh.cooser.protocol.RequestProto.HfData.Builder subBuilder = null;
              if (bodyCase_ == 6) {
                subBuilder = ((com.wonderzh.cooser.protocol.RequestProto.HfData) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.wonderzh.cooser.protocol.RequestProto.HfData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wonderzh.cooser.protocol.RequestProto.HfData) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 6;
              break;
            }
            case 58: {
              com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder subBuilder = null;
              if (bodyCase_ == 7) {
                subBuilder = ((com.wonderzh.cooser.protocol.RequestProto.Instruction) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.wonderzh.cooser.protocol.RequestProto.Instruction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wonderzh.cooser.protocol.RequestProto.Instruction) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 7;
              break;
            }
            case 66: {
              com.wonderzh.cooser.protocol.ResponseProto.Response.Builder subBuilder = null;
              if (bodyCase_ == 8) {
                subBuilder = ((com.wonderzh.cooser.protocol.ResponseProto.Response) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.wonderzh.cooser.protocol.ResponseProto.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wonderzh.cooser.protocol.ResponseProto.Response) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 8;
              break;
            }
            case 74: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (bodyCase_ == 9) {
                subBuilder = ((com.google.protobuf.Any) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.protobuf.Any) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 9;
              break;
            }
            case 82: {
              com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder subBuilder = null;
              if (bodyCase_ == 10) {
                subBuilder = ((com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.wonderzh.cooser.protocol.GenericProto.JsonObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 10;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wonderzh.cooser.protocol.MessageProto.internal_static_datameter_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wonderzh.cooser.protocol.MessageProto.internal_static_datameter_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wonderzh.cooser.protocol.MessageProto.Message.class, com.wonderzh.cooser.protocol.MessageProto.Message.Builder.class);
    }

    private int bodyCase_ = 0;
    private Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      LF_DATA(5),
      HF_DATA(6),
      INSTRUCTION(7),
      RESPONSE(8),
      ANY(9),
      JSON(10),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 5: return LF_DATA;
          case 6: return HF_DATA;
          case 7: return INSTRUCTION;
          case 8: return RESPONSE;
          case 9: return ANY;
          case 10: return JSON;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int MODE_FIELD_NUMBER = 1;
    private volatile Object mode_;
    /**
     * <code>string mode = 1;</code>
     * @return The mode.
     */
    @Override
    public String getMode() {
      Object ref = mode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mode_ = s;
        return s;
      }
    }
    /**
     * <code>string mode = 1;</code>
     * @return The bytes for mode.
     */
    @Override
    public com.google.protobuf.ByteString
        getModeBytes() {
      Object ref = mode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOL_FIELD_NUMBER = 2;
    private volatile Object protocol_;
    /**
     * <code>string protocol = 2;</code>
     * @return The protocol.
     */
    @Override
    public String getProtocol() {
      Object ref = protocol_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      }
    }
    /**
     * <code>string protocol = 2;</code>
     * @return The bytes for protocol.
     */
    @Override
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 3;
    private long uuid_;
    /**
     * <code>int64 uuid = 3;</code>
     * @return The uuid.
     */
    @Override
    public long getUuid() {
      return uuid_;
    }

    public static final int AUTHORIZATION_FIELD_NUMBER = 4;
    private volatile Object authorization_;
    /**
     * <code>string authorization = 4;</code>
     * @return The authorization.
     */
    @Override
    public String getAuthorization() {
      Object ref = authorization_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        authorization_ = s;
        return s;
      }
    }
    /**
     * <code>string authorization = 4;</code>
     * @return The bytes for authorization.
     */
    @Override
    public com.google.protobuf.ByteString
        getAuthorizationBytes() {
      Object ref = authorization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        authorization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LF_DATA_FIELD_NUMBER = 5;
    /**
     * <code>.request.LfData lf_data = 5;</code>
     * @return Whether the lfData field is set.
     */
    @Override
    public boolean hasLfData() {
      return bodyCase_ == 5;
    }
    /**
     * <code>.request.LfData lf_data = 5;</code>
     * @return The lfData.
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.LfData getLfData() {
      if (bodyCase_ == 5) {
         return (com.wonderzh.cooser.protocol.RequestProto.LfData) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
    }
    /**
     * <code>.request.LfData lf_data = 5;</code>
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder getLfDataOrBuilder() {
      if (bodyCase_ == 5) {
         return (com.wonderzh.cooser.protocol.RequestProto.LfData) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
    }

    public static final int HF_DATA_FIELD_NUMBER = 6;
    /**
     * <code>.request.HfData hf_data = 6;</code>
     * @return Whether the hfData field is set.
     */
    @Override
    public boolean hasHfData() {
      return bodyCase_ == 6;
    }
    /**
     * <code>.request.HfData hf_data = 6;</code>
     * @return The hfData.
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.HfData getHfData() {
      if (bodyCase_ == 6) {
         return (com.wonderzh.cooser.protocol.RequestProto.HfData) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
    }
    /**
     * <code>.request.HfData hf_data = 6;</code>
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder getHfDataOrBuilder() {
      if (bodyCase_ == 6) {
         return (com.wonderzh.cooser.protocol.RequestProto.HfData) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 7;
    /**
     * <code>.request.Instruction instruction = 7;</code>
     * @return Whether the instruction field is set.
     */
    @Override
    public boolean hasInstruction() {
      return bodyCase_ == 7;
    }
    /**
     * <code>.request.Instruction instruction = 7;</code>
     * @return The instruction.
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.Instruction getInstruction() {
      if (bodyCase_ == 7) {
         return (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
    }
    /**
     * <code>.request.Instruction instruction = 7;</code>
     */
    @Override
    public com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder getInstructionOrBuilder() {
      if (bodyCase_ == 7) {
         return (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_;
      }
      return com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 8;
    /**
     * <code>.response.Response response = 8;</code>
     * @return Whether the response field is set.
     */
    @Override
    public boolean hasResponse() {
      return bodyCase_ == 8;
    }
    /**
     * <code>.response.Response response = 8;</code>
     * @return The response.
     */
    @Override
    public com.wonderzh.cooser.protocol.ResponseProto.Response getResponse() {
      if (bodyCase_ == 8) {
         return (com.wonderzh.cooser.protocol.ResponseProto.Response) body_;
      }
      return com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
    }
    /**
     * <code>.response.Response response = 8;</code>
     */
    @Override
    public com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder() {
      if (bodyCase_ == 8) {
         return (com.wonderzh.cooser.protocol.ResponseProto.Response) body_;
      }
      return com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
    }

    public static final int ANY_FIELD_NUMBER = 9;
    /**
     * <code>.google.protobuf.Any any = 9;</code>
     * @return Whether the any field is set.
     */
    @Override
    public boolean hasAny() {
      return bodyCase_ == 9;
    }
    /**
     * <code>.google.protobuf.Any any = 9;</code>
     * @return The any.
     */
    @Override
    public com.google.protobuf.Any getAny() {
      if (bodyCase_ == 9) {
         return (com.google.protobuf.Any) body_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any any = 9;</code>
     */
    @Override
    public com.google.protobuf.AnyOrBuilder getAnyOrBuilder() {
      if (bodyCase_ == 9) {
         return (com.google.protobuf.Any) body_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    public static final int JSON_FIELD_NUMBER = 10;
    /**
     * <code>.generic.JsonObj json = 10;</code>
     * @return Whether the json field is set.
     */
    @Override
    public boolean hasJson() {
      return bodyCase_ == 10;
    }
    /**
     * <code>.generic.JsonObj json = 10;</code>
     * @return The json.
     */
    @Override
    public com.wonderzh.cooser.protocol.GenericProto.JsonObj getJson() {
      if (bodyCase_ == 10) {
         return (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_;
      }
      return com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
    }
    /**
     * <code>.generic.JsonObj json = 10;</code>
     */
    @Override
    public com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder getJsonOrBuilder() {
      if (bodyCase_ == 10) {
         return (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_;
      }
      return com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mode_);
      }
      if (!getProtocolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, protocol_);
      }
      if (uuid_ != 0L) {
        output.writeInt64(3, uuid_);
      }
      if (!getAuthorizationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authorization_);
      }
      if (bodyCase_ == 5) {
        output.writeMessage(5, (com.wonderzh.cooser.protocol.RequestProto.LfData) body_);
      }
      if (bodyCase_ == 6) {
        output.writeMessage(6, (com.wonderzh.cooser.protocol.RequestProto.HfData) body_);
      }
      if (bodyCase_ == 7) {
        output.writeMessage(7, (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_);
      }
      if (bodyCase_ == 8) {
        output.writeMessage(8, (com.wonderzh.cooser.protocol.ResponseProto.Response) body_);
      }
      if (bodyCase_ == 9) {
        output.writeMessage(9, (com.google.protobuf.Any) body_);
      }
      if (bodyCase_ == 10) {
        output.writeMessage(10, (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mode_);
      }
      if (!getProtocolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, protocol_);
      }
      if (uuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, uuid_);
      }
      if (!getAuthorizationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authorization_);
      }
      if (bodyCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.wonderzh.cooser.protocol.RequestProto.LfData) body_);
      }
      if (bodyCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (com.wonderzh.cooser.protocol.RequestProto.HfData) body_);
      }
      if (bodyCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_);
      }
      if (bodyCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, (com.wonderzh.cooser.protocol.ResponseProto.Response) body_);
      }
      if (bodyCase_ == 9) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, (com.google.protobuf.Any) body_);
      }
      if (bodyCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wonderzh.cooser.protocol.MessageProto.Message)) {
        return super.equals(obj);
      }
      com.wonderzh.cooser.protocol.MessageProto.Message other = (com.wonderzh.cooser.protocol.MessageProto.Message) obj;

      if (!getMode()
          .equals(other.getMode())) return false;
      if (!getProtocol()
          .equals(other.getProtocol())) return false;
      if (getUuid()
          != other.getUuid()) return false;
      if (!getAuthorization()
          .equals(other.getAuthorization())) return false;
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 5:
          if (!getLfData()
              .equals(other.getLfData())) return false;
          break;
        case 6:
          if (!getHfData()
              .equals(other.getHfData())) return false;
          break;
        case 7:
          if (!getInstruction()
              .equals(other.getInstruction())) return false;
          break;
        case 8:
          if (!getResponse()
              .equals(other.getResponse())) return false;
          break;
        case 9:
          if (!getAny()
              .equals(other.getAny())) return false;
          break;
        case 10:
          if (!getJson()
              .equals(other.getJson())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUuid());
      hash = (37 * hash) + AUTHORIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorization().hashCode();
      switch (bodyCase_) {
        case 5:
          hash = (37 * hash) + LF_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getLfData().hashCode();
          break;
        case 6:
          hash = (37 * hash) + HF_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getHfData().hashCode();
          break;
        case 7:
          hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
          hash = (53 * hash) + getInstruction().hashCode();
          break;
        case 8:
          hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getResponse().hashCode();
          break;
        case 9:
          hash = (37 * hash) + ANY_FIELD_NUMBER;
          hash = (53 * hash) + getAny().hashCode();
          break;
        case 10:
          hash = (37 * hash) + JSON_FIELD_NUMBER;
          hash = (53 * hash) + getJson().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wonderzh.cooser.protocol.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wonderzh.cooser.protocol.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code datameter.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datameter.Message)
        com.wonderzh.cooser.protocol.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wonderzh.cooser.protocol.MessageProto.internal_static_datameter_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wonderzh.cooser.protocol.MessageProto.internal_static_datameter_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wonderzh.cooser.protocol.MessageProto.Message.class, com.wonderzh.cooser.protocol.MessageProto.Message.Builder.class);
      }

      // Construct using com.wonderzh.cooser.protocol.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mode_ = "";

        protocol_ = "";

        uuid_ = 0L;

        authorization_ = "";

        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wonderzh.cooser.protocol.MessageProto.internal_static_datameter_Message_descriptor;
      }

      @Override
      public com.wonderzh.cooser.protocol.MessageProto.Message getDefaultInstanceForType() {
        return com.wonderzh.cooser.protocol.MessageProto.Message.getDefaultInstance();
      }

      @Override
      public com.wonderzh.cooser.protocol.MessageProto.Message build() {
        com.wonderzh.cooser.protocol.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.wonderzh.cooser.protocol.MessageProto.Message buildPartial() {
        com.wonderzh.cooser.protocol.MessageProto.Message result = new com.wonderzh.cooser.protocol.MessageProto.Message(this);
        result.mode_ = mode_;
        result.protocol_ = protocol_;
        result.uuid_ = uuid_;
        result.authorization_ = authorization_;
        if (bodyCase_ == 5) {
          if (lfDataBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = lfDataBuilder_.build();
          }
        }
        if (bodyCase_ == 6) {
          if (hfDataBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = hfDataBuilder_.build();
          }
        }
        if (bodyCase_ == 7) {
          if (instructionBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = instructionBuilder_.build();
          }
        }
        if (bodyCase_ == 8) {
          if (responseBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = responseBuilder_.build();
          }
        }
        if (bodyCase_ == 9) {
          if (anyBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = anyBuilder_.build();
          }
        }
        if (bodyCase_ == 10) {
          if (jsonBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = jsonBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wonderzh.cooser.protocol.MessageProto.Message) {
          return mergeFrom((com.wonderzh.cooser.protocol.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wonderzh.cooser.protocol.MessageProto.Message other) {
        if (other == com.wonderzh.cooser.protocol.MessageProto.Message.getDefaultInstance()) return this;
        if (!other.getMode().isEmpty()) {
          mode_ = other.mode_;
          onChanged();
        }
        if (!other.getProtocol().isEmpty()) {
          protocol_ = other.protocol_;
          onChanged();
        }
        if (other.getUuid() != 0L) {
          setUuid(other.getUuid());
        }
        if (!other.getAuthorization().isEmpty()) {
          authorization_ = other.authorization_;
          onChanged();
        }
        switch (other.getBodyCase()) {
          case LF_DATA: {
            mergeLfData(other.getLfData());
            break;
          }
          case HF_DATA: {
            mergeHfData(other.getHfData());
            break;
          }
          case INSTRUCTION: {
            mergeInstruction(other.getInstruction());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case ANY: {
            mergeAny(other.getAny());
            break;
          }
          case JSON: {
            mergeJson(other.getJson());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wonderzh.cooser.protocol.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wonderzh.cooser.protocol.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private Object mode_ = "";
      /**
       * <code>string mode = 1;</code>
       * @return The mode.
       */
      public String getMode() {
        Object ref = mode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mode = 1;</code>
       * @return The bytes for mode.
       */
      public com.google.protobuf.ByteString
          getModeBytes() {
        Object ref = mode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mode = 1;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {

        mode_ = getDefaultInstance().getMode();
        onChanged();
        return this;
      }
      /**
       * <code>string mode = 1;</code>
       * @param value The bytes for mode to set.
       * @return This builder for chaining.
       */
      public Builder setModeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        mode_ = value;
        onChanged();
        return this;
      }

      private Object protocol_ = "";
      /**
       * <code>string protocol = 2;</code>
       * @return The protocol.
       */
      public String getProtocol() {
        Object ref = protocol_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          protocol_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string protocol = 2;</code>
       * @return The bytes for protocol.
       */
      public com.google.protobuf.ByteString
          getProtocolBytes() {
        Object ref = protocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          protocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string protocol = 2;</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {

        protocol_ = getDefaultInstance().getProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 2;</code>
       * @param value The bytes for protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        protocol_ = value;
        onChanged();
        return this;
      }

      private long uuid_ ;
      /**
       * <code>int64 uuid = 3;</code>
       * @return The uuid.
       */
      @Override
      public long getUuid() {
        return uuid_;
      }
      /**
       * <code>int64 uuid = 3;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(long value) {

        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uuid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {

        uuid_ = 0L;
        onChanged();
        return this;
      }

      private Object authorization_ = "";
      /**
       * <code>string authorization = 4;</code>
       * @return The authorization.
       */
      public String getAuthorization() {
        Object ref = authorization_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          authorization_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string authorization = 4;</code>
       * @return The bytes for authorization.
       */
      public com.google.protobuf.ByteString
          getAuthorizationBytes() {
        Object ref = authorization_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          authorization_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorization = 4;</code>
       * @param value The authorization to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorization(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        authorization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorization = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorization() {

        authorization_ = getDefaultInstance().getAuthorization();
        onChanged();
        return this;
      }
      /**
       * <code>string authorization = 4;</code>
       * @param value The bytes for authorization to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        authorization_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.LfData, com.wonderzh.cooser.protocol.RequestProto.LfData.Builder, com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder> lfDataBuilder_;
      /**
       * <code>.request.LfData lf_data = 5;</code>
       * @return Whether the lfData field is set.
       */
      @Override
      public boolean hasLfData() {
        return bodyCase_ == 5;
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       * @return The lfData.
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.LfData getLfData() {
        if (lfDataBuilder_ == null) {
          if (bodyCase_ == 5) {
            return (com.wonderzh.cooser.protocol.RequestProto.LfData) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
        } else {
          if (bodyCase_ == 5) {
            return lfDataBuilder_.getMessage();
          }
          return com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
        }
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      public Builder setLfData(com.wonderzh.cooser.protocol.RequestProto.LfData value) {
        if (lfDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          lfDataBuilder_.setMessage(value);
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      public Builder setLfData(
          com.wonderzh.cooser.protocol.RequestProto.LfData.Builder builderForValue) {
        if (lfDataBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          lfDataBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      public Builder mergeLfData(com.wonderzh.cooser.protocol.RequestProto.LfData value) {
        if (lfDataBuilder_ == null) {
          if (bodyCase_ == 5 &&
              body_ != com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance()) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.LfData.newBuilder((com.wonderzh.cooser.protocol.RequestProto.LfData) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 5) {
            lfDataBuilder_.mergeFrom(value);
          }
          lfDataBuilder_.setMessage(value);
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      public Builder clearLfData() {
        if (lfDataBuilder_ == null) {
          if (bodyCase_ == 5) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 5) {
            bodyCase_ = 0;
            body_ = null;
          }
          lfDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      public com.wonderzh.cooser.protocol.RequestProto.LfData.Builder getLfDataBuilder() {
        return getLfDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder getLfDataOrBuilder() {
        if ((bodyCase_ == 5) && (lfDataBuilder_ != null)) {
          return lfDataBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 5) {
            return (com.wonderzh.cooser.protocol.RequestProto.LfData) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
        }
      }
      /**
       * <code>.request.LfData lf_data = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.LfData, com.wonderzh.cooser.protocol.RequestProto.LfData.Builder, com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder>
          getLfDataFieldBuilder() {
        if (lfDataBuilder_ == null) {
          if (!(bodyCase_ == 5)) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.LfData.getDefaultInstance();
          }
          lfDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wonderzh.cooser.protocol.RequestProto.LfData, com.wonderzh.cooser.protocol.RequestProto.LfData.Builder, com.wonderzh.cooser.protocol.RequestProto.LfDataOrBuilder>(
                  (com.wonderzh.cooser.protocol.RequestProto.LfData) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 5;
        onChanged();;
        return lfDataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.HfData, com.wonderzh.cooser.protocol.RequestProto.HfData.Builder, com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder> hfDataBuilder_;
      /**
       * <code>.request.HfData hf_data = 6;</code>
       * @return Whether the hfData field is set.
       */
      @Override
      public boolean hasHfData() {
        return bodyCase_ == 6;
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       * @return The hfData.
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.HfData getHfData() {
        if (hfDataBuilder_ == null) {
          if (bodyCase_ == 6) {
            return (com.wonderzh.cooser.protocol.RequestProto.HfData) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
        } else {
          if (bodyCase_ == 6) {
            return hfDataBuilder_.getMessage();
          }
          return com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
        }
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      public Builder setHfData(com.wonderzh.cooser.protocol.RequestProto.HfData value) {
        if (hfDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          hfDataBuilder_.setMessage(value);
        }
        bodyCase_ = 6;
        return this;
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      public Builder setHfData(
          com.wonderzh.cooser.protocol.RequestProto.HfData.Builder builderForValue) {
        if (hfDataBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          hfDataBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 6;
        return this;
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      public Builder mergeHfData(com.wonderzh.cooser.protocol.RequestProto.HfData value) {
        if (hfDataBuilder_ == null) {
          if (bodyCase_ == 6 &&
              body_ != com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance()) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.HfData.newBuilder((com.wonderzh.cooser.protocol.RequestProto.HfData) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 6) {
            hfDataBuilder_.mergeFrom(value);
          }
          hfDataBuilder_.setMessage(value);
        }
        bodyCase_ = 6;
        return this;
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      public Builder clearHfData() {
        if (hfDataBuilder_ == null) {
          if (bodyCase_ == 6) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 6) {
            bodyCase_ = 0;
            body_ = null;
          }
          hfDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      public com.wonderzh.cooser.protocol.RequestProto.HfData.Builder getHfDataBuilder() {
        return getHfDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder getHfDataOrBuilder() {
        if ((bodyCase_ == 6) && (hfDataBuilder_ != null)) {
          return hfDataBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 6) {
            return (com.wonderzh.cooser.protocol.RequestProto.HfData) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
        }
      }
      /**
       * <code>.request.HfData hf_data = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.HfData, com.wonderzh.cooser.protocol.RequestProto.HfData.Builder, com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder>
          getHfDataFieldBuilder() {
        if (hfDataBuilder_ == null) {
          if (!(bodyCase_ == 6)) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.HfData.getDefaultInstance();
          }
          hfDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wonderzh.cooser.protocol.RequestProto.HfData, com.wonderzh.cooser.protocol.RequestProto.HfData.Builder, com.wonderzh.cooser.protocol.RequestProto.HfDataOrBuilder>(
                  (com.wonderzh.cooser.protocol.RequestProto.HfData) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 6;
        onChanged();;
        return hfDataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.Instruction, com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder, com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder> instructionBuilder_;
      /**
       * <code>.request.Instruction instruction = 7;</code>
       * @return Whether the instruction field is set.
       */
      @Override
      public boolean hasInstruction() {
        return bodyCase_ == 7;
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       * @return The instruction.
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.Instruction getInstruction() {
        if (instructionBuilder_ == null) {
          if (bodyCase_ == 7) {
            return (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
        } else {
          if (bodyCase_ == 7) {
            return instructionBuilder_.getMessage();
          }
          return com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
        }
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      public Builder setInstruction(com.wonderzh.cooser.protocol.RequestProto.Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          instructionBuilder_.setMessage(value);
        }
        bodyCase_ = 7;
        return this;
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      public Builder setInstruction(
          com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          instructionBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 7;
        return this;
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      public Builder mergeInstruction(com.wonderzh.cooser.protocol.RequestProto.Instruction value) {
        if (instructionBuilder_ == null) {
          if (bodyCase_ == 7 &&
              body_ != com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance()) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.Instruction.newBuilder((com.wonderzh.cooser.protocol.RequestProto.Instruction) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 7) {
            instructionBuilder_.mergeFrom(value);
          }
          instructionBuilder_.setMessage(value);
        }
        bodyCase_ = 7;
        return this;
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      public Builder clearInstruction() {
        if (instructionBuilder_ == null) {
          if (bodyCase_ == 7) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 7) {
            bodyCase_ = 0;
            body_ = null;
          }
          instructionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      public com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder getInstructionBuilder() {
        return getInstructionFieldBuilder().getBuilder();
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      @Override
      public com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder getInstructionOrBuilder() {
        if ((bodyCase_ == 7) && (instructionBuilder_ != null)) {
          return instructionBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 7) {
            return (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_;
          }
          return com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
        }
      }
      /**
       * <code>.request.Instruction instruction = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.RequestProto.Instruction, com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder, com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder>
          getInstructionFieldBuilder() {
        if (instructionBuilder_ == null) {
          if (!(bodyCase_ == 7)) {
            body_ = com.wonderzh.cooser.protocol.RequestProto.Instruction.getDefaultInstance();
          }
          instructionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wonderzh.cooser.protocol.RequestProto.Instruction, com.wonderzh.cooser.protocol.RequestProto.Instruction.Builder, com.wonderzh.cooser.protocol.RequestProto.InstructionOrBuilder>(
                  (com.wonderzh.cooser.protocol.RequestProto.Instruction) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 7;
        onChanged();;
        return instructionBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.ResponseProto.Response, com.wonderzh.cooser.protocol.ResponseProto.Response.Builder, com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.response.Response response = 8;</code>
       * @return Whether the response field is set.
       */
      @Override
      public boolean hasResponse() {
        return bodyCase_ == 8;
      }
      /**
       * <code>.response.Response response = 8;</code>
       * @return The response.
       */
      @Override
      public com.wonderzh.cooser.protocol.ResponseProto.Response getResponse() {
        if (responseBuilder_ == null) {
          if (bodyCase_ == 8) {
            return (com.wonderzh.cooser.protocol.ResponseProto.Response) body_;
          }
          return com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
        } else {
          if (bodyCase_ == 8) {
            return responseBuilder_.getMessage();
          }
          return com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
        }
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      public Builder setResponse(com.wonderzh.cooser.protocol.ResponseProto.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bodyCase_ = 8;
        return this;
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      public Builder setResponse(
          com.wonderzh.cooser.protocol.ResponseProto.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 8;
        return this;
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      public Builder mergeResponse(com.wonderzh.cooser.protocol.ResponseProto.Response value) {
        if (responseBuilder_ == null) {
          if (bodyCase_ == 8 &&
              body_ != com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance()) {
            body_ = com.wonderzh.cooser.protocol.ResponseProto.Response.newBuilder((com.wonderzh.cooser.protocol.ResponseProto.Response) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 8) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        bodyCase_ = 8;
        return this;
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (bodyCase_ == 8) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 8) {
            bodyCase_ = 0;
            body_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      public com.wonderzh.cooser.protocol.ResponseProto.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      @Override
      public com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder() {
        if ((bodyCase_ == 8) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 8) {
            return (com.wonderzh.cooser.protocol.ResponseProto.Response) body_;
          }
          return com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
        }
      }
      /**
       * <code>.response.Response response = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.ResponseProto.Response, com.wonderzh.cooser.protocol.ResponseProto.Response.Builder, com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(bodyCase_ == 8)) {
            body_ = com.wonderzh.cooser.protocol.ResponseProto.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wonderzh.cooser.protocol.ResponseProto.Response, com.wonderzh.cooser.protocol.ResponseProto.Response.Builder, com.wonderzh.cooser.protocol.ResponseProto.ResponseOrBuilder>(
                  (com.wonderzh.cooser.protocol.ResponseProto.Response) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 8;
        onChanged();;
        return responseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anyBuilder_;
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       * @return Whether the any field is set.
       */
      @Override
      public boolean hasAny() {
        return bodyCase_ == 9;
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       * @return The any.
       */
      @Override
      public com.google.protobuf.Any getAny() {
        if (anyBuilder_ == null) {
          if (bodyCase_ == 9) {
            return (com.google.protobuf.Any) body_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (bodyCase_ == 9) {
            return anyBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      public Builder setAny(com.google.protobuf.Any value) {
        if (anyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          anyBuilder_.setMessage(value);
        }
        bodyCase_ = 9;
        return this;
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      public Builder setAny(
          com.google.protobuf.Any.Builder builderForValue) {
        if (anyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          anyBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 9;
        return this;
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      public Builder mergeAny(com.google.protobuf.Any value) {
        if (anyBuilder_ == null) {
          if (bodyCase_ == 9 &&
              body_ != com.google.protobuf.Any.getDefaultInstance()) {
            body_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 9) {
            anyBuilder_.mergeFrom(value);
          }
          anyBuilder_.setMessage(value);
        }
        bodyCase_ = 9;
        return this;
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      public Builder clearAny() {
        if (anyBuilder_ == null) {
          if (bodyCase_ == 9) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 9) {
            bodyCase_ = 0;
            body_ = null;
          }
          anyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      public com.google.protobuf.Any.Builder getAnyBuilder() {
        return getAnyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      @Override
      public com.google.protobuf.AnyOrBuilder getAnyOrBuilder() {
        if ((bodyCase_ == 9) && (anyBuilder_ != null)) {
          return anyBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 9) {
            return (com.google.protobuf.Any) body_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any any = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
          getAnyFieldBuilder() {
        if (anyBuilder_ == null) {
          if (!(bodyCase_ == 9)) {
            body_ = com.google.protobuf.Any.getDefaultInstance();
          }
          anyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 9;
        onChanged();;
        return anyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.GenericProto.JsonObj, com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder, com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder> jsonBuilder_;
      /**
       * <code>.generic.JsonObj json = 10;</code>
       * @return Whether the json field is set.
       */
      @Override
      public boolean hasJson() {
        return bodyCase_ == 10;
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       * @return The json.
       */
      @Override
      public com.wonderzh.cooser.protocol.GenericProto.JsonObj getJson() {
        if (jsonBuilder_ == null) {
          if (bodyCase_ == 10) {
            return (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_;
          }
          return com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
        } else {
          if (bodyCase_ == 10) {
            return jsonBuilder_.getMessage();
          }
          return com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
        }
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      public Builder setJson(com.wonderzh.cooser.protocol.GenericProto.JsonObj value) {
        if (jsonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          jsonBuilder_.setMessage(value);
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      public Builder setJson(
          com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder builderForValue) {
        if (jsonBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          jsonBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      public Builder mergeJson(com.wonderzh.cooser.protocol.GenericProto.JsonObj value) {
        if (jsonBuilder_ == null) {
          if (bodyCase_ == 10 &&
              body_ != com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance()) {
            body_ = com.wonderzh.cooser.protocol.GenericProto.JsonObj.newBuilder((com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 10) {
            jsonBuilder_.mergeFrom(value);
          }
          jsonBuilder_.setMessage(value);
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      public Builder clearJson() {
        if (jsonBuilder_ == null) {
          if (bodyCase_ == 10) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 10) {
            bodyCase_ = 0;
            body_ = null;
          }
          jsonBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      public com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder getJsonBuilder() {
        return getJsonFieldBuilder().getBuilder();
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      @Override
      public com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder getJsonOrBuilder() {
        if ((bodyCase_ == 10) && (jsonBuilder_ != null)) {
          return jsonBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 10) {
            return (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_;
          }
          return com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
        }
      }
      /**
       * <code>.generic.JsonObj json = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wonderzh.cooser.protocol.GenericProto.JsonObj, com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder, com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder>
          getJsonFieldBuilder() {
        if (jsonBuilder_ == null) {
          if (!(bodyCase_ == 10)) {
            body_ = com.wonderzh.cooser.protocol.GenericProto.JsonObj.getDefaultInstance();
          }
          jsonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wonderzh.cooser.protocol.GenericProto.JsonObj, com.wonderzh.cooser.protocol.GenericProto.JsonObj.Builder, com.wonderzh.cooser.protocol.GenericProto.JsonObjOrBuilder>(
                  (com.wonderzh.cooser.protocol.GenericProto.JsonObj) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 10;
        onChanged();;
        return jsonBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datameter.Message)
    }

    // @@protoc_insertion_point(class_scope:datameter.Message)
    private static final com.wonderzh.cooser.protocol.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wonderzh.cooser.protocol.MessageProto.Message();
    }

    public static com.wonderzh.cooser.protocol.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public com.wonderzh.cooser.protocol.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datameter_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datameter_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022MessageProto.proto\022\tdatameter\032\031google/" +
      "protobuf/any.proto\032\022RequestProto.proto\032\023" +
      "ResponseProto.proto\032\022GenericProto.proto\"" +
      "\272\002\n\007Message\022\014\n\004mode\030\001 \001(\t\022\020\n\010protocol\030\002 " +
      "\001(\t\022\014\n\004uuid\030\003 \001(\003\022\025\n\rauthorization\030\004 \001(\t" +
      "\022\"\n\007lf_data\030\005 \001(\0132\017.request.LfDataH\000\022\"\n\007" +
      "hf_data\030\006 \001(\0132\017.request.HfDataH\000\022+\n\013inst" +
      "ruction\030\007 \001(\0132\024.request.InstructionH\000\022&\n" +
      "\010response\030\010 \001(\0132\022.response.ResponseH\000\022#\n" +
      "\003any\030\t \001(\0132\024.google.protobuf.AnyH\000\022 \n\004js" +
      "on\030\n \001(\0132\020.generic.JsonObjH\000B\006\n\004bodyB2\n\"" +
      "com.wonderzh.cooser.protocolB\014Mess" +
      "ageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.wonderzh.cooser.protocol.RequestProto.getDescriptor(),
          com.wonderzh.cooser.protocol.ResponseProto.getDescriptor(),
          com.wonderzh.cooser.protocol.GenericProto.getDescriptor(),
        });
    internal_static_datameter_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datameter_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datameter_Message_descriptor,
        new String[] { "Mode", "Protocol", "Uuid", "Authorization", "LfData", "HfData", "Instruction", "Response", "Any", "Json", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.wonderzh.cooser.protocol.RequestProto.getDescriptor();
    com.wonderzh.cooser.protocol.ResponseProto.getDescriptor();
    com.wonderzh.cooser.protocol.GenericProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
